name: Accessibility Check

on:
  workflow_dispatch

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
