name: Accessibility Check

on:
  workflow_dispatch

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
